<?php
/**
 * fbEmailGetJSON
 *
 * DEPRECATED. Form data is now directly taken from CB properties field in fbValidateProcessJSON.
 *
 * A snippet for FormBlocks that grabs the raw JSON data from the Properties column of the site_content table.
 * This data is being generated by ContentBlocks, and is used on the website to display the actual form.
 *
 * The result is being fed to the SIMPLX Widgeteer snippet.
 * This snippet is used to automatically generate the email template, based on the CB JSON data. It will template the JSON into rows for each field.
 * By using the complete output (and not f.i. cbGetFieldContent), the order of the fields is always correct in the email.
 *
 * @author Hugo Peek
 */

$resourceID = $modx->getOption('formID', $scriptProperties, '');
$resource = $modx->getObject('modResource', $resourceID);

$rawData = $resource->getProperty('linear', 'contentblocks');
$json = json_encode($rawData);

return $json;