[[cbHasField? &field=`[[++formblocks.cb_input_file_multiple_id]]` &then=`AjaxUpload2Formit,AjaxUploadAttachments,`]]
[[cbGetFieldContent:notempty=`AjaxUploadRequired,`? &field=`[[++formblocks.cb_input_file_multiple_id:empty=`-1`]]` &fieldSettingFilter=`field_required==1`]]
[[cbHasField? &field=`[[++formblocks.cb_input_file_id]]` &then=`fbProcessUploads,`]]
[[cbHasField? &field=`[[++formblocks.cb_math_question_id]]` &then=`math,`]]
[[++romanesco.dev_mode:isnot=`1`:then=`[[++formblocks.antispam_hooks:append=`,`]]`]]
[[+save_form:eq=`1`:then=`FormItSaveForm,`]]
[[*fb_hooks:append=`,`]]
[[If? &subject=`[[*fb_email_to_dynamic:empty=`[[*fb_email_to]]`]]` &operator=`notempty` &then=`email,`]]
[[*fb_store_attachments:replace=`default==[[++formblocks.store_attachments]]`:isnot=`1`:then=`AjaxUploadRemove,`]] [[- BUG: gives warning if setting is off and AjaxUpload is not installed.]]
[[*fb_autoresponder_toggle:eq=`1`:then=`FormItAutoResponder,`]]
[[++formblocks.formsource:eq=`1`:then=`formsource_reset,`]]
[[*fb_posthooks:append=`,`]]