[[[[If?
    &subject=`[[!isEditor]]`
    &operator=`notempty`
    &then=`$richTextMessage?
        &heading=`[[+heading]]`
        &content=`[[+value]]`
        &message_type=`[[+message_type]]`
        &size=`[[+size]]`
        &close=`[[+close]]`
    `
]]]]