[[If:toPlaceholder=`bg[[+id]][[+idx]][[+imgScale]].img_uncropped`?
    &subject=`[[+image.crops.mobile.url:empty=``]][[+image.crops.tablet.url:empty=``]][[+image.crops.desktop.url:empty=``]]`
    &operand=`empty`
    &then=`
    [[pthumb:imgOptimizeThumb=`[[+quality:empty=`[[++img_quality]]`]]`:prepend=`url(`:append=`)`?
        &input=`[[+image.url:prepend=`/`]]`
        &options=`w=[[+imgWidth]]
            &q=[[++romanesco.img_quality]]
            &scale=[[+imgScale:default=`1`]]
        `
    ]]`
    &else=``
]]
[[If:toPlaceholder=`bg[[+id]][[+idx]][[+imgScale]].img_src`?
    &subject=`[[+image.crops.[[+imgType]].url]]`
    &operator=`notempty`
    &then=`
    [[pthumb:imgOptimizeThumb=`[[+quality:empty=`[[++img_quality]]`]]`:prepend=`url(`:append=`)`?
        &input=`[[+image.url:prepend=`/`]]`
        &options=`w=[[+imgWidth]]
            &sx=[[If? &subject=`[[+image.crops.[[+imgType]].x]]` &operator=`lt` &operand=`0` &then=`0` &else=`[[+image.crops.[[+imgType]].x]]`]]
            &sy=[[If? &subject=`[[+image.crops.[[+imgType]].y]]` &operator=`lt` &operand=`0` &then=`0` &else=`[[+image.crops.[[+imgType]].y]]`]]
            &sw=[[+image.crops.[[+imgType]].width]]
            &sh=[[+image.crops.[[+imgType]].height]]
            &q=[[++romanesco.img_quality]]
            &scale=[[+imgScale:default=`1`]]
        `
    ]]`
    &else=`[[+bg[[+id]][[+idx]][[+imgScale]].img_uncropped]]`
]]
[[If:empty=`[[+gradient]]`?
    &subject=`[[+image.extension]]`
    &operator=`is`
    &operand=`svg`
    &then=`[[+image.url:prepend=`url(/`:append=`)`]]`
    &else=`[[+bg[[+id]][[+idx]][[+imgScale]].img_src]]`
]]
[[+position:empty=`center center`]] /
[[+size:empty=`cover`]]
[[+repeat]]
[[+attachment]]