[[!AjaxUpload?
    &uid=`[[+name]]`
    &maxFiles=`[[+upload_limit]]`
    &maxFilesizeMb=`[[+max_file_size]]`
    &allowedExtensions=`[[+allowed_file_types]]`
    &thumbX=`150`
    &thumbY=`150`
    &addCss=`0`
]]