Article regular=overviewRowArticleBasic
Article regular (Card)=overviewRowArticleBasicCard
Article image=overviewRowArticleImageBasic
Article image (Card)=overviewRowArticleImageTopCard
Article compact=overviewRowArticleCompact
Article quote=overviewRowArticleQuote