[[+toc_type:contains=`dropdown`:then=`
<div id="dropdown-toc" class="[[+toc_type:contains=`list`:then=`hidden element`]]">
    [[$tocNavDropdown]]
</div>
`]]
[[+toc_type:contains=`list`:then=`
<div class="[[+toc_type:contains=`dropdown`:then=`mobile hidden`]]">
    <p>[[%romanesco.toc.menu_title]]</p>
    <nav id="content-menu" class="ui [[+size]] vertical text menu toc">
        [[- Menu items are generated by the TableOfContents plugin]]
    </nav>
</div>
`]]
[[!tableOfContents?
    &target=`[[+toc_type:eq=`dropdown`:then=`#dropdown-toc .menu`:else=`#content-menu`]]`
]]