[[+toc_type:contains=`dropdown`:then=`
<div id="dropdown-toc" class="[[+toc_type:contains=`list`:then=`hidden element`]]">
    [[$tocNavDropdown]]
</div>
`]]
[[+toc_type:contains=`list`:then=`
<nav id="content-menu" class="ui [[+size:default=`large`]] vertical text menu toc [[+toc_type:contains=`dropdown`:then=`tablet or lower hidden`]]">
    [[- Menu items are generated by the TableOfContents plugin]]
</nav>
`]]
[[!tableOfContents?
    &target=`[[+toc_type:eq=`dropdown`:then=`#dropdown-toc .menu`:else=`#content-menu`]]`
]]