<div id="submenu-dropdown" class="ui vertical stripe segment hidden element">
    <div class="ui container">
        <div class="ui large very long fluid selection dropdown">
            <i class="dropdown icon"></i>
            <div class="default text">[[%romanesco.toc.dropdown_title]]</div>
            <nav class="toc menu">[[- Menu items are moved here on mobile]]</nav>
        </div>
    </div>
</div>

<nav id="submenu" class="ui large secondary vertical fluid right pointing [[+sticky:eq=`1`:then=`sticky`]] toc menu tablet or lower hidden">
    [[- Menu items are generated by the TableOfContents plugin]]
</nav>