[[[[++social_sharing_channels:contains=`facebook`:then=`$buttonSocialShareFacebook? &classes=`[[+button_type]]` &uid=`[[+unique_idx]]``]]]]
[[[[++social_sharing_channels:contains=`twitter`:then=`$buttonSocialShareTwitter? &classes=`[[+button_type]]` &uid=`[[+unique_idx]]``]]]]
[[[[++social_sharing_channels:contains=`googleplus`:then=`$buttonSocialShareGoogleplus? &classes=`[[+button_type]]` &uid=`[[+unique_idx]]``]]]]
[[[[++social_sharing_channels:contains=`linkedin`:then=`$buttonSocialShareLinkedin? &classes=`[[+button_type]]` &uid=`[[+unique_idx]]``]]]]
[[[[++social_sharing_channels:contains=`pinterest`:then=`$buttonSocialSharePinterest? &classes=`[[+button_type]]` &uid=`[[+unique_idx]]``]]]]
[[$socialShareButtonsTheme? &uid=`[[+unique_idx]]`]]