/*******************************
    CUSTOM CSS

    Global additions to Semantic UI styles, based on site content and settings.
    This mostly contains the Global Backgrounds.

    DO NOT EDIT DIRECTLY!

    Generated by MODX when saving the Global Backgrounds.
    If you want to add styling that needs to access MODX placeholders, then
     create a globalBackgroundsTheme or globalCustomCSS chunk somewhere. It will
     be picked up at the bottom of this chunk.
    If you don't need placeholders, then just add the styling in your Semantic
     site or theme folder.

*******************************/

@import url("/[[++romanesco.semantic_css_path]]/backgrounds[[++minify_css_js:eq=`1`:then=`.min`]].css");


/* Load all backgrounds set under Global Content */

[[pdoResources?
    &parents=`[[++romanesco.global_backgrounds_id]]`
    &limit=`0`
    &depth=`0`
    &showUnpublished=`1`
    &tpl=`globalBackgroundCSS`
    &where=`{"template:=":"27"}`
    &tvPrefix=``
]]

/* Load additional backgrounds for given context */

[[pdoResources?
    &parents=`[[++romanesco.global_backgrounds_id]]`
    &limit=`0`
    &showUnpublished=`1`
    &tpl=`globalBackgroundCSS`
    &where=`[{"template:=":"27"},{"uri:LIKE":"%/[[+context]]/%"}]`
    &tvPrefix=``
]]


/* Load all backgrounds based on an overview image */

[[pdoResources?
    [[+context:notempty=`&context=`[[+context]]``]]
    &parents=`0`
    &limit=`0`
    &showUnpublished=`1`
    &tpl=`globalBackgroundImgOverviewCSS`
    &includeTVs=`overview_img_pano,overview_img_wide`
    &processTVs=`1`
    &tvFilters=`header_background_img!==`
    &tvPrefix=``
]]


/* Additional styles */

[[[[If?
    &subject=`globalBackgroundsTheme`
    &operator=`iselement`
    &operand=`chunk`
    &then=`$globalBackgroundsTheme? &context=`[[+context:empty=`web`]]``
    &else=``
]]]]
[[[[If?
    &subject=`globalCustomCSS`
    &operator=`iselement`
    &operand=`chunk`
    &then=`$globalCustomCSS? &context=`[[+context:empty=`web`]]``
    &else=``
]]]]